spring:
  application:
    name: highload-testing-presentation
  datasource:
    url: jdbc:postgresql://localhost:5434/highload_testing_db
    username: highload_testing_user
    password: highload_testing_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=60s

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,beans,conditions
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
